-- Unify chat models: Channel → Conversation (+ type/dmKey/lastMessageAt),
-- ChannelMessage → Message (+ clientId/editedAt/deletedAt/replyToId/searchText),
-- ChannelRead → ConversationRead (+ muted), new ConversationMember, and
-- rebuilt MessageReaction/Poll whose DDL references the renamed tables.
--
-- SQLite cannot relax NOT NULL or rename through Prisma's diff (it sees a
-- drop+create), so this is a hand-edited rebuild: create the new tables
-- (DDL generated by `prisma migrate diff`, kept verbatim), copy every row,
-- then drop the old tables. Existing data — including the seeded
-- chan_general / chan_bestyrelse channels — survives with ids intact.
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;

-- CreateTable
CREATE TABLE "Conversation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL DEFAULT 'CHANNEL',
    "key" TEXT,
    "name" TEXT,
    "description" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,
    "requiredRole" TEXT,
    "dmKey" TEXT,
    "createdById" TEXT,
    "lastMessageAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Conversation_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ConversationMember" (
    "conversationId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "isAdmin" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("conversationId", "userId"),
    CONSTRAINT "ConversationMember_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Message" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conversationId" TEXT NOT NULL,
    "authorId" TEXT,
    "body" TEXT NOT NULL,
    "clientId" TEXT,
    "editedAt" DATETIME,
    "deletedAt" DATETIME,
    "searchText" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "replyToId" TEXT,
    "eventId" TEXT,
    "eventDate" TEXT,
    CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Message_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Message_replyToId_fkey" FOREIGN KEY ("replyToId") REFERENCES "Message" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Message_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "CalendarEvent" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ConversationRead" (
    "userId" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "lastReadAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "muted" BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY ("userId", "conversationId"),
    CONSTRAINT "ConversationRead_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationRead_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Copy data: every existing channel becomes a CHANNEL conversation with the
-- same id, so nothing referencing a channel id breaks.
INSERT INTO "Conversation" ("id", "type", "key", "name", "description", "order", "requiredRole", "createdAt")
SELECT "id", 'CHANNEL', "key", "name", "description", "order", "requiredRole", "createdAt" FROM "Channel";

INSERT INTO "Message" ("id", "conversationId", "authorId", "body", "createdAt", "eventId", "eventDate")
SELECT "id", "channelId", "authorId", "body", "createdAt", "eventId", "eventDate" FROM "ChannelMessage";

INSERT INTO "ConversationRead" ("userId", "conversationId", "lastReadAt")
SELECT "userId", "channelId", "lastReadAt" FROM "ChannelRead";

-- RedefineTables: MessageReaction and Poll DDL references the renamed
-- tables, so both are rebuilt under their own names (PollOption/PollVote
-- reference "Poll" by name and stay valid).
CREATE TABLE "new_MessageReaction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "messageId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "emoji" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MessageReaction_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "Message" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MessageReaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_MessageReaction" ("createdAt", "emoji", "id", "messageId", "userId") SELECT "createdAt", "emoji", "id", "messageId", "userId" FROM "MessageReaction";
DROP TABLE "MessageReaction";
ALTER TABLE "new_MessageReaction" RENAME TO "MessageReaction";
CREATE INDEX "MessageReaction_messageId_idx" ON "MessageReaction"("messageId");
CREATE UNIQUE INDEX "MessageReaction_messageId_userId_emoji_key" ON "MessageReaction"("messageId", "userId", "emoji");

CREATE TABLE "new_Poll" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conversationId" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "multiple" BOOLEAN NOT NULL DEFAULT false,
    "closesAt" DATETIME,
    "createdById" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Poll_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Poll_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "Message" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Poll_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
-- Hand-fixed versus the generated script: carry channelId over as
-- conversationId (the diff would have dropped it).
INSERT INTO "new_Poll" ("closesAt", "conversationId", "createdAt", "createdById", "id", "messageId", "multiple", "question")
SELECT "closesAt", "channelId", "createdAt", "createdById", "id", "messageId", "multiple", "question" FROM "Poll";
DROP TABLE "Poll";
ALTER TABLE "new_Poll" RENAME TO "Poll";
CREATE UNIQUE INDEX "Poll_messageId_key" ON "Poll"("messageId");

-- DropTable (indexes drop with their tables)
DROP TABLE "ChannelRead";
DROP TABLE "ChannelMessage";
DROP TABLE "Channel";

-- Backfills
UPDATE "Conversation" SET "lastMessageAt" = (
  SELECT MAX(m."createdAt") FROM "Message" m WHERE m."conversationId" = "Conversation"."id"
);
-- ASCII lowercase is fine for historical rows; new writes lowercase in JS
-- (locale-aware, handles Æ/Ø/Å).
UPDATE "Message" SET "searchText" = lower("body");

-- CreateIndex
CREATE UNIQUE INDEX "Conversation_key_key" ON "Conversation"("key");

-- CreateIndex
CREATE UNIQUE INDEX "Conversation_dmKey_key" ON "Conversation"("dmKey");

-- CreateIndex
CREATE INDEX "Conversation_order_idx" ON "Conversation"("order");

-- CreateIndex
CREATE INDEX "ConversationMember_userId_idx" ON "ConversationMember"("userId");

-- CreateIndex
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId", "createdAt");

PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
